id: I1FB6AAE9
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-06-29T16:12:39.329825'
last_modified: '2022-06-29T16:12:39.329837'
parser: null
source_metadata:
  title: 'Śāntideva: Bodhicaryāvatāra'
  language: fr
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
